//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_.frm.comm_.ajaxDyna
{


	public partial class DoneUncover
	{

		/// <summary>
		/// Frm_comm__ajaxDyna_DoneUncover1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.frm.comm_.ajaxDyna.frm_comm__ajaxDyna_DoneUncover Frm_comm__ajaxDyna_DoneUncover1;
	}
}
