//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB._CTR_._Demo_web.tabs_.vertical_.navi._stuffed
{


	public partial class Ctr
	{
	}
}
