//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB._CTR_._Demo_web.tabs_.vertical_.navi._stuffed {
    
    
    public partial class Js {
        
        /// <summary>
        /// Tabs_vertical__Navi1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web._ctr_.WEB._CTR_.tabs_.vertical_.tabs_vertical__Navi Tabs_vertical__Navi1;
        
        /// <summary>
        /// OnLoadScript1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul._web_._CTR_.OnLoadScript OnLoadScript1;
    }
}
