//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_ {
    
    
    public partial class Alert {
        
        /// <summary>
        /// Alert_heritFroCtrA1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web.ctr._web._ctr.Alert_heritFroCtrA Alert_heritFroCtrA1;
        
        /// <summary>
        /// Alert1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web.ctr._web._ctr.Alert Alert1;
    }
}
