//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web.ctr._web._ctr._Demo_web {
    
    
    public partial class LabelEmailValidator {
        
        /// <summary>
        /// CommonScriptsControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web.js._web._ctr.CommonScriptsControl3 CommonScriptsControl2;
        
        /// <summary>
        /// LabelEmailValidator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web.ctr._web._ctr.LabelEmailValidator LabelEmailValidator1;
    }
}
