//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_.urlAssignable
{


	public partial class UrlAssign
	{

		/// <summary>
		/// Ajax_cors_failMsged_Fill1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.ajax.cors.failMsged.ajax_cors_failMsged_Fill Ajax_cors_failMsged_Fill1;

		/// <summary>
		/// UrlAssignable__urlAssign_js_OnLoad1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.urlAssignable._urlAssign.js.urlAssignable__urlAssign_js_OnLoad UrlAssignable__urlAssign_js_OnLoad1;

		/// <summary>
		/// Filable__fil_js_OnLoad1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.filable._fil.js.filable__fil_js_OnLoad Filable__fil_js_OnLoad1;
	}
}
