//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_.frm._fit
{


	public partial class Feed
	{

		/// <summary>
		/// Txt_err_email_Cached1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.txt.err.email.txt_err_email_Cached Txt_err_email_Cached1;

		/// <summary>
		/// _feed_js_Onload1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_._feed.js._feed_js_Onload _feed_js_Onload1;
	}
}
