//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_.frm
{


	public partial class Fit
	{

		/// <summary>
		/// Frm1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.Frm Frm1;

		/// <summary>
		/// Feed control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB.CTR._DEMO_.frm._fit.Feed Feed;

		/// <summary>
		/// Script__onLoad_Dollar1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul._web_._CTR_.script_.onLoad_.script__onLoad_Dollar Script__onLoad_Dollar1;
	}
}
