//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_.WEB.CTR._DEMO_.time.bound_.day_
{


	public partial class LeNow
	{

		/// <summary>
		/// Time_bound__day__LeNow1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_.WEB._CTR_.time.bound_.day_.time_bound__day__LeNow Time_bound__day__LeNow1;
	}
}
